stan-core:
  stanPath: .stan
  includes: []
  excludes:
    - '*.local'
    - assets
    - CHANGELOG.md
    - docs
    - diagrams/**
    - package-lock.json
  imports:
    stan-cli:
      - ../stan-cli/.stan/interop/stan-core/**
      - ../stan-cli/guides/stan-assistant-guide.md
stan-cli:
  scripts:
    typecheck: npm run typecheck
    lint: npm run lint:fix
    test: npm run test -- --no-color
    build:
      script: cross-env NO_COLOR=1 npm run build
      warnPattern: (?:^loaded [\w.]+ with warnings$|^\(!\)\s+(?!Circular dependency).+) (?![\s\S]*outputToFilesystem option is defaulting to true) (?![\s\S]*\(!\)\s+Circular dependency[\s\S]*node_modules[\\/](?:zod)[\s\S]*)
    docs: npm run docs -- --emit none
    knip: npm run knip
  cliDefaults:
    run:
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
